/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"

#define USER_LED_PIN 5      // Port A
#define USER_BUTTON  13     // Port C

void delay(void)
{
    for(uint32_t i =0; i < 50000; i++) {}
}

void InitUserPushButton(GPIO_Handle_t hGPIO, uint8_t PinNumber)
{
    hGPIO.PinConfig.PinNumber = PinNumber;
    hGPIO.PinConfig.PinMode = MODE_INPUT;
    hGPIO.PinConfig.PinPuPdControl = RSTR_NONE;
    GPIO_SetClock(hGPIO.GPIOx, ENABLE);
    GPIO_Init(&hGPIO);
}

void InitUserLed(GPIO_Handle_t hGPIO, uint8_t PinNumber)
{
    hGPIO.PinConfig.PinNumber = PinNumber;
    hGPIO.PinConfig.PinMode = MODE_OUTPUT;
    hGPIO.PinConfig.PinSpeed = SPEED_HIGH;
    hGPIO.PinConfig.PinPuPdControl = RSTR_NONE;
    hGPIO.PinConfig.PinOPType = TYPE_PUSHPULL;
    GPIO_SetClock(hGPIO.GPIOx, ENABLE);
    GPIO_Init(&hGPIO);
}

int main(void)
{
    GPIO_Handle_t hGPIOA = *GetGPIOPortHandler(GPIOA);
    InitUserLed(hGPIOA, USER_LED_PIN);

    GPIO_Handle_t hGPIOC = *GetGPIOPortHandler(GPIOC);
    InitUserPushButton(hGPIOC, USER_BUTTON); // Push button is connected to PC13

    while(1)
    {
        if (GPIO_PinRead(&hGPIOC, USER_BUTTON) == OFF)
        {
            GPIO_TogglePin(&hGPIOA, USER_LED_PIN);
            delay();
        }
        else
        {
            GPIO_PinWrite(&hGPIOA, USER_LED_PIN, OFF);
        }
    }
	return 0;
}
